# Generated by Django 3.2.5 on 2021-07-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recentwork',
            old_name='Image',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='recentwork',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Work title'),
        ),
    ]
